### PR TITLE
v2.0.0

### PR DESCRIPTION
**Pull request by walexnelson**
This is a major release as there are breaking changes to the way the main client is instantiated and the expected params for some of the client methods.

1 Rewritten in TypeScript (Targets ES6)
2 Require array of scopes as part of the `DomoClient` instantiation. 
3 Removed pre-request access validation
4 Added post-request intercept to renew access token if 401 is returned. The initial request is then sent again. 
5 moved PDP methods into their own client to mirror the JavaSDK structure

2-4 should address PR #3

### CODE REVIEW

**Comment by walexnelson** [comment]
@checketts who should review this?

**Comment by checketts** [comment]
> @checketts who should review this?

@iammerrick Do you have any suggestions?

**Comment by iammerrick** [comment]
Yup! @cletusw & @justspamjustin both have great TypeScript, Domo  & Node.js exposure. :-)

**Comment by checketts** [comment]
FYI @nicksrandall could you look this over?

**Comment by nicksrandall** [comment]
I read over all the code and everything looks great! My only thought is that we should probably list the minimum node version that we plan to support. The package.json [engine](https://docs.npmjs.com/files/package.json#engines) field might be a good place for that.

**Comment by walexnelson** [comment]
@nicksrandall I put `>=6.4.0` as the node engine as the `tsconfig` is targeting ES6 and Node6.4 seems to have pretty [decent Es6 coverage](http://node.green/) and it's definitely covering anything that this library is using.

do you see any reason to target ES5 instead? Node4 is still LTS but not much longer... I think I'd have to add some polyfills if we go that route.

**Comment by walexnelson** [comment]
@nicksrandall @checketts any reason not to merge this now? (see my prior comment about the node engine)

**Comment by checketts** [comment]
Fine by me. I'm relying in Nick's Node expertise.

**Comment by walexnelson** [comment]
@checketts I don't have access to merge this if you're waiting on me.

**Comment by checketts** [comment]
Access granted

**Pull request merged**
